# Generated by Django 6.0.1 on 2026-02-09 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="category",
            field=models.CharField(
                choices=[
                    ("FOOD", "Food & Drinks"),
                    ("TRANSPORT", "Transport"),
                    ("BILLS", "Utilities/Bills"),
                    ("SHOPPING", "Shopping"),
                    ("SALARY", "Salary"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
